namespace EatSmart.Logic
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    using EatSmart.Logic.Models;

    public class FoodInfoFetcher
    {
        private Lazy<Dictionary<string, FoodInfo>> foodInfo = new Lazy<Dictionary<string, FoodInfo>>(InitializeInfo);
        
        public IEnumerable<FoodInfo> GetAllInfos()
        {
            return this.foodInfo.Value.Values;
        }

        public FoodInfo GetInfo(string name)
        {
            if (this.foodInfo.Value.ContainsKey(name))
            {
                return this.foodInfo.Value[name];
            }

            return null;
        }

        private static Dictionary<string, FoodInfo> InitializeInfo()
        {
            var allInfos = new List<FoodInfo>()
            {
                new FoodInfo(150, "1 cup", "Full-fat milk"),
new FoodInfo(102, "1 cup", "Low fat milk (1%)"),
new FoodInfo(157, "1 cup", "Cow's milk"),
new FoodInfo(264, "1 cup", "Goat milk"), 
new FoodInfo(123, "28 g", "Sweetened Condensed Milk cans"), 
new FoodInfo(635, "Half a cup", "Full cream milk powder"), 
new FoodInfo(435, "Half a cup", "Skim milk powder"), 
new FoodInfo(208, "1 cup", "Full-fat chocolate milk"), 
new FoodInfo(244, "1 cup", "Strawberry Milk"), 
new FoodInfo(114, "Slice, 28 gm", "Cheddar cheese slices"), 
new FoodInfo(75, "28 g", "Feta cheese"), 
new FoodInfo(110, "25 g", "Finuta cheese"), 
new FoodInfo(101, "28 g", "Gouda cheese"), 
new FoodInfo(80, "28 g", "Mozzarella cheese"), 
new FoodInfo(80, "28 g", "Kraft Cheese cups"), 
new FoodInfo(98, "28 g", "Edam cheese"), 
new FoodInfo(104, "28 g", "Blue cheese"), 
new FoodInfo(116, "28 g", "Harafati cheese"), 
new FoodInfo(128, "28 g", "Mascarpone cheese"), 
new FoodInfo(216, "Half a cup", "Ricotta cheese whole milk"), 
new FoodInfo(171, "Half a cup", "Ricotta cheese, partly skim milk"), 
new FoodInfo(130, "28 g", "Parmesan cheese"), 
new FoodInfo(86, "28 g", "Camembert cheese"), 
new FoodInfo(99, "100 g", "Cottage cheese"), 
new FoodInfo(289, "100 g", "Akkawi cheese"), 
new FoodInfo(404, "100 g", "Kashkaval cheese"), 
new FoodInfo(363, "100 g", "Halloumi cheese"), 
new FoodInfo(52, "1 spoon", "Cream focused"), 
new FoodInfo(37, "1 spoon", "Cream Medium"), 
new FoodInfo(141, "1 spoon", "Rob yogurt full-fat"), 
new FoodInfo(114, "1 spoon", "Rob yogurt skim"), 
new FoodInfo(105, "155 g", "Brick"), 
new FoodInfo(99, "1 cup", "Clabber"), 
new FoodInfo(135, "Half a cup", "Vanilla ice cream 10% fat"), 
new FoodInfo(240, "1 ball", "Ice Cream"), 
new FoodInfo(280, "1 ball", "Vanilla"), 
new FoodInfo(220, "1 ball", "Cocoa"), 
new FoodInfo(72, "Half a cup", "Apple juice"), 
new FoodInfo(78, "Half a cup", "Apricot juice, canned"), 
new FoodInfo(3, "Spoon to eat", "Grape juice, canned"), 
new FoodInfo(59, "Half a cup", "Lemon juice canned"), 
new FoodInfo(52, "Half a cup", "Fresh orange juice"), 
new FoodInfo(58, "Half a cup", "Canned orange juice"), 
new FoodInfo(47, "Half a cup", "Grapefruit juice, canned local"), 
new FoodInfo(67, "Half a cup", "Grapefruit juice, unsweetened"), 
new FoodInfo(75, "Half a cup", "Canned peach juice"), 
new FoodInfo(70, "Half a cup", "Canned pear juice"), 
new FoodInfo(21, "Half a cup", "Canned pineapple juice"), 
new FoodInfo(49, "Half a cup", "Canned tomato juice"), 
new FoodInfo(175, "One cup", "Canned juice Islands"), 
new FoodInfo(110, "One cup", "Guava juice"), 
new FoodInfo(165, "One cup", "Mango juice"), 
new FoodInfo(5, "Teaspoon", "Nescafe coffee without sugar"), 
new FoodInfo(5, "Teaspoon", "Instant coffee without caffeine"), 
new FoodInfo(1, "One cup", "Tea without sugar"), 
new FoodInfo(5, "One cup", "American coffee"), 
new FoodInfo(100, "240 ml cup", "Pepsi-Cola"), 
new FoodInfo(0.00, "240 ml cup", "Diet Pepsi-Cola"), 
new FoodInfo(90, "240 ml cup", "Seven Up"), 
new FoodInfo(96, "240 ml cup", "Sprite"), 
new FoodInfo(119, "240 ml cup", "Fanta"), 
new FoodInfo(97, "240 ml cup", "Coca-Cola"), 
new FoodInfo(1.00, "240 ml cup", "Diet Coca-Cola"), 
new FoodInfo(126, "240 ml cup", "Cream soda"), 
new FoodInfo(107, "240 ml cup", "Drink grape gas"), 
new FoodInfo(142, "Approx. 42 g", "Beef"), 
new FoodInfo(40, "28 g", "Pastrami - turkey"), 
new FoodInfo(141, "28 g", "Pepperoni beef"), 
new FoodInfo(56, "28 g", "Salami - turkey"), 
new FoodInfo(72, "28 g", "Salami - beef"), 
new FoodInfo(47, "28 g", "Mortadella - beef"), 
new FoodInfo(57, "28 g", "Bologna sausage"), 
new FoodInfo(88,"28 g", "Turkey"), 
new FoodInfo(102, "Beef", "Frankfurter"), 
new FoodInfo(116, "42 g", "Turkey"), 
new FoodInfo(17, "One, big", "Egg whites, (fresh or iced)"), 
new FoodInfo(59, "One, big", "Fresh egg yolk"), 
new FoodInfo(79, "One, big", "Full cook boiled eggs"), 
new FoodInfo(91, "One, big", "Fried eggs"), 
new FoodInfo(92, "One, big", "Omelet"), 
new FoodInfo(252, "113 g", "Omelet with cheese and vegetables"), 
new FoodInfo(130, "One, big", "Duck eggs"), 
new FoodInfo(267, "One, big", "Goose eggs"), 
new FoodInfo(135, "One, big", "Turkey eggs"), 
new FoodInfo(14, "One, big", "Quail eggs"), 
new FoodInfo(380, "Half a cup, 60 g", "Nuts"), 
new FoodInfo(209, "Quarter a cup", "Almonds, dry"), 
new FoodInfo(160, "28 g", "Cashew, roasted, dry"), 
new FoodInfo(165, "28 g", "Cashew, roasted, oily"), 
new FoodInfo(170, "28 g", "Nuts, roasted, dry"), 
new FoodInfo(176, "28 g", "Hazelnut, roasted, oily"), 
new FoodInfo(215, "Half a cup", "Lentils, whole, green"), 
new FoodInfo(210, "One cup", "Lentils, cooked"), 
new FoodInfo(105, "1 Tablespoon", "Margarine"), 
new FoodInfo(120, "1 Tablespoon", "Olive oil"), 
new FoodInfo(120, "1 Tablespoon", "Sunflower oil"), 
new FoodInfo(114, "1 Tablespoon", "Sheep fat"), 
new FoodInfo(126, "1 Tablespoon", "Vegetable oil"), 
new FoodInfo(125, "1 Tablespoon", "Beef fat"), 
new FoodInfo(36, "1 Tablespoon", "Butter"), 
new FoodInfo(120, "1 Tablespoon", "Corn oil"), 
new FoodInfo(81, "Medium, 140 g", "Apples"), 
new FoodInfo(17, "Medium, 30 g", "Apricot"), 
new FoodInfo(105, "Medium, 100 g", "Banana"), 
new FoodInfo(37, "One, 40 g", "Fig"), 
new FoodInfo(38, "Half", "Grapefruit"), 
new FoodInfo(49, "10 beads", "Cherries"), 
new FoodInfo(162, "Half", "Avocado"), 
new FoodInfo(53, "Half a cup", "Grapes"), 
new FoodInfo(45, "One, 85 g", "Guava"), 
new FoodInfo(46, "One, 76 g", "Kiwi"), 
new FoodInfo(68, "Half, 85 g", "Mango"), 
new FoodInfo(62, "One, 110 g", "Orange"), 
new FoodInfo(117, "Medium", "Papaya"), 
new FoodInfo(37, "One, 85 g", "Peach"), 
new FoodInfo(98, "Medium, 170 g", "Pear"), 
new FoodInfo(42, "Slice, 82 g", "Pineapple"), 
new FoodInfo(36, "One, 60 g", "Plum"), 
new FoodInfo(110, "Medium, 150 g", "Pomegranate"), 
new FoodInfo(67, "Medium, 142 g", "Nectarine"), 
new FoodInfo(26, "Piece, 100 g", "Watermelon"), 
new FoodInfo(33, "Piece, 100 g", "Melon"), 
new FoodInfo(23, "Half a cup", "Strawberries"), 
new FoodInfo(37, "One, 85 g", "Tangerine"), 
new FoodInfo(122, "One cup", "Blueberry"), 
new FoodInfo(150, "10 beads", "Rutab/ripe dates"), 
new FoodInfo(49, "100 g", "Loquat"), 
new FoodInfo(52, "100 g", "Plum"), 
new FoodInfo(17, "One, 60 g", "Lemon"), 
new FoodInfo(53, "Fruit size", "Sweet Lemon"), 
new FoodInfo(117, "One cup", "Black berry"), 
new FoodInfo(9, "30 beads", "Nabq (rhamnus)"), 
new FoodInfo(60, "Medium", "Quince"), 
new FoodInfo(82, "Half a cup", "Tamarind"), 
new FoodInfo(111, "Half a cup", "Canned apricots (with sugar syrup)"), 
new FoodInfo(94, "Half a cup", "Fruit salad (with sugar syrup)"), 
new FoodInfo(107, "Half a cup", "Canned cherry (with thick sugar syrup)"), 
new FoodInfo(95, "Half a cup", "Canned peaches (with sugar syrup)"), 
new FoodInfo(94, "Half a cup", "Canned pear with (with sugar syrup)"), 
new FoodInfo(100, "Half a cup", "Canned pineapple (with sugar syrup)"), 
new FoodInfo(26, "One", "Dried dates"), 
new FoodInfo(288, "100 g", "Dried figs"), 
new FoodInfo(109, "Half a cup", "Raisins"), 
new FoodInfo(113, "Half a cup", "Dried plum"), 
new FoodInfo(169, "Half a cup", "Dried Apricots"), 
new FoodInfo(7, "1 teaspoon", "Cardamom"), 
new FoodInfo(13, "3 teaspoons", "Dried hot red pepper"), 
new FoodInfo(7, "1 teaspoon", "Cinnamon"), 
new FoodInfo(6, "1 teaspoon", "Cloves"), 
new FoodInfo(6, "1 teaspoon", "Latency"), 
new FoodInfo(1, "1 teaspoon", "Ginger powder"), 
new FoodInfo(20, "One, medium", "Ginger root"), 
new FoodInfo(9, "1 teaspoon", "Nutmeg powder"), 
new FoodInfo(8, "1 teaspoon", "Black pepper"), 
new FoodInfo(220, "63 g", "Lamb shoulder, cooked with fat"), 
new FoodInfo(135, "48 g", "Lamb shoulder, cooked without fat"), 
new FoodInfo(205, "85 g", "Lamb thigh, roasted with fat"), 
new FoodInfo(140, "73 g", "Lamb thigh, roasted without fat"), 
new FoodInfo(200, "85 g", "Lamb rib, grilled without fat"), 
new FoodInfo(307, "85 g", "Lamb rib, grilled with fat"), 
new FoodInfo(189, "85 g", "Beef, chest, cooked"), 
new FoodInfo(183, "85 g", "Beef shoulder, without fat"), 
new FoodInfo(245, "85 g", "Beef, minced and cooked"), 
new FoodInfo(317, "85 g", "Shawarma, only meat"), 
new FoodInfo(174, "85 g", "Beef steak without fat"), 
new FoodInfo(133, "85 g", "Tekkah"), 
new FoodInfo(226, "85 g", "Kebab"), 
new FoodInfo(281, "85 g", "Kubba, stuffed"), 
new FoodInfo(182, "85 g", "Slices without fat"), 
new FoodInfo(148, "85 g", "Cow heart, cooked"), 
new FoodInfo(122, "85 g", "Cow kidney,  cooked"), 
new FoodInfo(241, "85 g", "Cow tongue, cooked"), 
new FoodInfo(31, "60 g", "Carrot"), 
new FoodInfo(35, "Half a cup", "Carrot, cooked"), 
new FoodInfo(15, "Half a cup", "Cauliflower, cooked"), 
new FoodInfo(12, "Half a cup", "Cauliflower, uncooked"), 
new FoodInfo(7, "Half a cup", "Cucumbers, chopped"), 
new FoodInfo(100, "Half a cup", "Fried eggplant"), 
new FoodInfo(13, "Half a cup", "Eggplant, cooked"), 
new FoodInfo(20, "Half a cup", "Green beans, cooked"), 
new FoodInfo(25, "Half a cup", "Green beans, canned"), 
new FoodInfo(16, "Half a cup", "Cabbage, cooked"), 
new FoodInfo(8, "Half a cup", "Cabbage, uncooked"), 
new FoodInfo(10, "Half a cup", "Celery"), 
new FoodInfo(77, "One, medium", "Corn"), 
new FoodInfo(9, "Half a cup", "Mushrooms, fresh"), 
new FoodInfo(19, "Half a cup", "Mushroom, canned"), 
new FoodInfo(4, "Half a cup", "Lettuce"), 
new FoodInfo(54, "Half a cup", "Mixed vegetables (a variety of vegetables cooked together)"), 
new FoodInfo(25, "Half a cup", "Okra, cooked and chopped"), 
new FoodInfo(27, "Half a cup", "Fresh onions, chopped"), 
new FoodInfo(16, "Half a cup", "Green onions, chopped"), 
new FoodInfo(67, "Half a cup", "Green peas, cooked"), 
new FoodInfo(12, "Half a cup", "Peppers, chopped"), 
new FoodInfo(18, "One, 30 g", "Hot pepper"), 
new FoodInfo(220, "195 g", "Baked potato, with the peel"), 
new FoodInfo(162, "195 g", "Baked potato, without the peel"), 
new FoodInfo(158, "10 pieces, 42 g", "Fried potato"), 
new FoodInfo(14, "Half a cup", "Shalgam kale, boiled"), 
new FoodInfo(2, "Half a cup", "Watercress"), 
new FoodInfo(41, "Half a cup", "Squash"), 
new FoodInfo(7, "10 grains, 40 g", "Red rweid radish"), 
new FoodInfo(9, "10 leaves, medium", "Red rweid radish, leaves"), 
new FoodInfo(6, "Half a cup", "Chopped spinach"), 
new FoodInfo(18, "Half a cup", "Zucchini, chopped and cooked"), 
new FoodInfo(111, "Half a cup", "Sweet potatoes, mashed"), 
new FoodInfo(26, "One, medium", "Red tomatoes"), 
new FoodInfo(73, "One cup", "Green beans"), 
new FoodInfo(46, "One cup", "Beet"), 
new FoodInfo(73, "One cup", "Cabbage"), 
new FoodInfo(1, "1 Spoon, minced", "Leek"), 
new FoodInfo(97, "1 package", "Coriander"), 
new FoodInfo(25, "1 package", "Fenugreek, leaves"), 
new FoodInfo(7, "5 pieces of garlic peeled", "Garlic"), 
new FoodInfo(146, "1 cup", "Grape leaves"), 
new FoodInfo(84, "Package, medium", "Mint"), 
new FoodInfo(95, "10 grains, medium", "Black olives"), 
new FoodInfo(66, "10 grains, medium", "Green olives"), 
new FoodInfo(34, "1 cup, minced", "Parsley"), 
new FoodInfo(25, "Package, medium", "Parsley"), 
new FoodInfo(58, "Package, medium", "White rweid radishes"), 
new FoodInfo(14, "1 Cup, chopped", "Spinach"), 
new FoodInfo(31, "1 cup, chopped", "Zucchini"), 
new FoodInfo(40, "One, medium", "Zucchini"), 
new FoodInfo(50, "100 g", "Basil"), 
new FoodInfo(32, "100 g", "Boil"), 
new FoodInfo(32, "100 g", "Legume"), 
new FoodInfo(82, "100 g", "Sugar-cane"), 
new FoodInfo(17, "100 g", "Bread, cereals"), 
new FoodInfo(70, "Quarter of a loaf", "Lebanese bread"), 
new FoodInfo(79, "Quarter of a loaf", "Oven bread, Iranian"), 
new FoodInfo(130, "One, 50 g", "Whole wheat bread"), 
new FoodInfo(208, "One, 75 g", "Manaqich (bread with thyme)"), 
new FoodInfo(209, "One, 75 g", "Sammon"), 
new FoodInfo(150, "50 g", "Rusk (cake)"), 
new FoodInfo(190, "Small, 130 g", "Pasta with sauce"), 
new FoodInfo(95, "Cup, 25 g", "Corn flakes"), 
new FoodInfo(333, "Quarter of a loaf, 115 g", "French bread"), 
new FoodInfo(178, "4 pieces, 55 g", "Plain biscuits"), 
new FoodInfo(131, "Half a cup", "White rice, cooked (long grain)"), 
new FoodInfo(61, "A slice", "Brown toast"), 
new FoodInfo(64, "A slice", "Plain white toast"), 
new FoodInfo(99, "Half a cup", "Spaghetti, cooked or pasta"), 
new FoodInfo(110, "Half a cup", "Spaghetti, cooked with minced meat and tomato"), 
new FoodInfo(154, "Half a cup", "Lasagna with meat sauce"), 
new FoodInfo(672, "One cup", "Barley"), 
new FoodInfo(344, "One cup", "Pasta"), 
new FoodInfo(471, "One cup", "Cornstarch"), 
new FoodInfo(675, "One cup", "Rice, uncooked"), 
new FoodInfo(354, "One cup", "Rice powder"), 
new FoodInfo(99, "One cup", "Vermicelli (balaleet)"), 
new FoodInfo(613, "One cup", "Bulgur (groats, crushed)"), 
new FoodInfo(485, "One cup", "Wheat"), 
new FoodInfo(225, "One, medium", "Jabati (Indian bread)"), 
new FoodInfo(167, "85 g", "Chicken leg (hip), without skin, grilled"), 
new FoodInfo(223, "85 g", "Chicken leg (hip), with skin, grilled"), 
new FoodInfo(142, "Half a breast", "Chicken breast, without skin, grilled"), 
new FoodInfo(193, "Half a breast", "Chicken breast, with skin, grilled"), 
new FoodInfo(161, "Half a breast", "Chicken breast, without skin, fried"), 
new FoodInfo(99, "1 wing 35.5 g", "Chicken wings, with skin, grilled"), 
new FoodInfo(290, "6 pieces 104 g", "Chicken pieces, vacuum, fried"), 
new FoodInfo(238, "85 g", "Chicken gizzards, fried"), 
new FoodInfo(135, "85 g", "Chicken livers, cooked"), 
new FoodInfo(173, "85 g", "Duck meat, without skin, roasted"), 
new FoodInfo(161, "85 g", "Kinds of Turkey Meat"), 
new FoodInfo(190, "85 g", "Red dark meat, without skin"), 
new FoodInfo(135, "85 g", "Red dark meat, with skin"), 
new FoodInfo(169, "85 g", "Red light meat, meat without skin"), 
new FoodInfo(58, "28 g", "Sardines, canned in oil"), 
new FoodInfo(42, "21 g", "Anchovies, canned in oil"), 
new FoodInfo(104, "85 g", "Tuna, canned in water"), 
new FoodInfo(169, "85 g", "Tuna, canned in oil"), 
new FoodInfo(99, "85 g", "Smoked salmon"), 
new FoodInfo(136, "85 g", "Grilled Fish"), 
new FoodInfo(228, "3 pieces, 85 g", "Fish fried with rusk"), 
new FoodInfo(206, "85 g", "Shrimp fried with rusk"), 
new FoodInfo(84, "85 g", "Crab, canned"), 
new FoodInfo(83, "85 g", "Shrimp, cooked"), 
new FoodInfo(23, "28 g", "Oyster, uncooked"), 
new FoodInfo(46, "28 g", "Oysters, fried"), 
new FoodInfo(84, "85 g", "Oysters, fried with rusk"), 
new FoodInfo(40, "1 tablespoon", "Caviar, black or red"), 
new FoodInfo(187, "One cup", "Beans, boiled"), 
new FoodInfo(349, "One cup", "Dry beans"), 
new FoodInfo(37, "Half a cup", "Beans"), 
new FoodInfo(269, "Half a cup", "Chickpeas, boiled"), 
new FoodInfo(339, "One cup", "Flour"), 
new FoodInfo(192, "Half a cup", "Lentil"), 
new FoodInfo(170, "28 g", "Nuts mixed with roasted and dry peanuts"), 
new FoodInfo(175, "28 g", "Mixed nuts roasted in oil"), 
new FoodInfo(170, "28 g", "Sunflower seeds, roasted and dry"), 
new FoodInfo(175, "28 g", "Sunflower seed, roasted in oil"), 
new FoodInfo(357, "Half a cup", "Pistachios, dry and roasted"), 
new FoodInfo(165, "28 g", "Peanuts, dry and roasted"), 
new FoodInfo(170, "28 g", "Peanuts, roasted in oil"), 
new FoodInfo(95, "Spoon 16 g", "Peanut butter"), 
new FoodInfo(44, "28 g", "Roasted chestnut"), 
new FoodInfo(100, "28 g", "Coconut"), 
new FoodInfo(59, "28 g", "Grated coconut"), 
new FoodInfo(127, "28 g", "Roasted pumpkin seeds"), 
new FoodInfo(158, "28 g", "Dried watermelon seeds"), 
new FoodInfo(102.2, "28 g", "Circuit pills"), 
new FoodInfo(174.16, "28 g", "Sesame"), 
new FoodInfo(172.7, "28 g", "Pine")
            };

            var dict = new Dictionary<string, FoodInfo>();

            foreach (var item in allInfos)
            {
                dict.Add(item.Name, item);
            }

            return dict;
        }
    }
}
